version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678  # 设置 root 用户的密码
      MYSQL_DATABASE: BooksManagementSystemDB            # 创建的数据库
      MYSQL_USER: winx                 # 创建的普通用户
      MYSQL_PASSWORD: 12345678     # 普通用户的密码
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    build: .
    container_name: BooksManagementSystem
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/BooksManagementSystemDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge